### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by VitaliyAT** [McElast/Yandex_pictures_grabber#1]
FileNotFoundError: [WinError 3] Системе не удается найти указанный путь: 'D:/downs/космос'

How write WORD for search correctly if it few words?

**Comment by McElast** [comment]
Project is old, but still working.
The directory from PATH should exist. So you need to pass its location (manually create it). Then you can write few words in WORD.
For example, 'D:/downs/' - should exist or you can write any other existing on your PC folder
